name: Release

on:
  push:
    tags:
    - 'release[1]:*'
permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Test
      run: ./build/Build.ps1
      shell: pwsh
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./build/Push.ps1
      shell: pwsh
